name: package

on:
  push:
    branches:
      - main
      - feature/sync-doocs-new
  pull_request:
    branches:
      - main

jobs:
  package_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build:linux
      env:
        NODE_OPTIONS: "--experimental-global-webcrypto"
    - uses: actions/upload-artifact@v4
      with:
        name: linux
        path: |
          dist/*.AppImage
          dist/*.snap
          dist/*.deb
  package_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm build:mac
      env:
        NODE_OPTIONS: "--experimental-global-webcrypto"
    - uses: actions/upload-artifact@v4
      with:
        name: macos
        path: |
          dist/*.dmg
          dist/*.zip
  package_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build:win
      env:
        NODE_OPTIONS: "--experimental-global-webcrypto"
    - uses: actions/upload-artifact@v4
      with:
        name: windows
        path: |
          dist/*.exe
